#?? ??
server:
  port: 8080

spring:
  #MySQL ?? ??
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  #JPA ??
  jpa:
    hibernate:
      ddl-auto: create #DB ??? ??
    properties:
      hiberante:
        show_sql: true #???? ?? ?? ??
        format_sql: true #???? ???? ??? ???? ?? ???
    database-platform: org.hibernate.dialect.H2Dialect

facebook :
  client :
    clientId :
    clientSecret:
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link

google :
  client :
    clientId :
    clientSecret:
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    scope: email, profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

kakao :
  client :
    clientId :
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
  resource:
    userInfoUri: https://kapi.kakao.com/v1/user/me