#?? ??
server:
  port: 8080

spring:
  #MySQL ?? ??
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  #JPA ??
  jpa:
    hibernate:
      ddl-auto: create #DB ??? ??
    properties:
      hiberante:
        show_sql: true #???? ?? ?? ??
        format_sql: true #???? ???? ??? ???? ?? ???
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
          facebook:
            client-id:
            client-secret:

  custom:
    oauth2:
      kakao:
        client-id: